## Basic introduction to tensorflow - No neural networks

For more details: https://www.tensorflow.org/api_guides/python/

In [1]:
import numpy as np
import tensorflow as tf

### General procedure of tensorflow usage
1. assemble a computation graph
2. apply a session to run the operation in that graph

Every operation in a computation graph is regarded as a **node**. Edges between two nodes are data flows

#### 1. Usage of session

Session instance encapsulates the environment in which operations in a graph are executed to compute tensors (code part for computation)

* `tf.Session()`
* `.run()`

In [2]:
# Hello tensorflow
string = tf.constant('Hello tensorflow')

# recommender way for running session, will close the session 
with tf.Session() as sess:
    print(sess.run(string))

b'Hello tensorflow'


#### 2. Math operations

source: https://www.tensorflow.org/api_guides/python/math_ops

* `tf.constant(val, dtype = tf.[dtype], name = 'name')`
* `tf.add(a, b, name = 'name')`
* ...

In [3]:
x = tf.constant(2333.33, dtype = tf.float32, name = 'x')
y = tf.constant(666, dtype = tf.float32, name = 'y')

add_xy = tf.add(x, y, name = 'add_xy')
mul_xy = tf.multiply(x, y, name = 'mul_xy')

with tf.Session() as sess:
    print(sess.run([x, y, add_xy, mul_xy]))

[2333.3301, 666.0, 2999.3301, 1553997.9]


#### 3. Variables

Values can be updated

* `tf.Variable(val, dtype = tf.[dtype])`
* `tf.assign_[](val)`

NOTE: always **initialize** the variable and run before using it `init = tf.global_variables_initializer()`

In [4]:
x = tf.Variable([[0, 0], [0, 0]], dtype = tf.float32)
assign_x = x.assign([[1, 0], [0, 1]])

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init) # always
    print(sess.run(assign_x))

[[ 1.  0.]
 [ 0.  1.]]


#### 4. Tensor

Tensor is actually **ndarray**: 0-d array is scalar; 1-d array is vector; 2-d array is ...

* `tf.zeros(shape = [ , ], dtype = tf.[dtype], name = 'name')`
* `tf.ones(shape = [ , ], dtype = tf.[dtype], name = 'name')`
* `tf.linspace(start = , stop = , num = , name = 'name')`
* `tf.range(start = , limit = 7, delta = , name = 'name')`
* `tf.random_normal(shape = [ , ], mean = , stddev = )`

In [5]:
zero_array = tf.zeros(shape=[2,3], dtype=tf.float32, name = 'zero_array')
one_array = tf.ones(shape=[2,3], dtype=tf.float32, name = 'one_array')

template = tf.constant([[1,2,3],[4,5,6]], dtype = tf.float32, name = 'template') # Has [2,3] shape
zero_like = tf.zeros_like(template, name = 'zero_like')
one_like = tf.ones_like(template, name = 'one_like')

lin_seq = tf.linspace(start = 0.0, stop = 5.0, num = 5, name = 'lin_seq')
lin_range = tf.range(start = 0, limit = 7, delta = 1, name = 'lin_range')

norm_rnd = tf.random_normal(shape=[3, 3], mean = 0.0, stddev = 1.0)

with tf.Session() as sess:
    print('0 array:\n{}\n'.format(sess.run(zero_array)))
    print('1 array:\n{}\n'.format(sess.run(one_array)))
    print('0 inferred:\n{}\n'.format(sess.run(zero_like)))
    print('1 inferred:\n{}\n'.format(sess.run(one_like)))
    print('linear sequence:\n{}\n'.format(sess.run(lin_seq)))
    print('range:\n{}\n'.format(sess.run(lin_range)))
    print('Random normal:\n{}\n'.format(sess.run(norm_rnd)))

0 array:
[[ 0.  0.  0.]
 [ 0.  0.  0.]]

1 array:
[[ 1.  1.  1.]
 [ 1.  1.  1.]]

0 inferred:
[[ 0.  0.  0.]
 [ 0.  0.  0.]]

1 inferred:
[[ 1.  1.  1.]
 [ 1.  1.  1.]]

linear sequence:
[ 0.    1.25  2.5   3.75  5.  ]

range:
[0 1 2 3 4 5 6]

Random normal:
[[-0.47109124 -0.09817415  0.77889282]
 [-0.67207485 -1.74551499 -0.87530226]
 [ 0.67523015 -0.66725606  0.12565319]]



#### 5. Placeholder

Recommended way to feed data into network

* `x = tf.placeholder(shape = [ , ], dtype = tf.[dtype])`
* `.run(x, feed_dict = {x: feed_x})`

In [6]:
x_placeholder = tf.placeholder(shape = [3, 3], dtype = tf.float32)
tensor_rnd = tf.Variable(tf.random_normal(shape = [3, 1], mean = 0, stddev = 1, name = 'tensor_rnd'), dtype = tf.float32)
x_placeholder_mul = np.dot(x_placeholder, tensor_rnd)

init = tf.global_variables_initializer() # DO NOT FORGET INITILIZATION
feed_x = np.ones((3, 3))

with tf.Session() as mySess:
    mySess.run(init)
    print(mySess.run(x_placeholder_mul, feed_dict = {x_placeholder: feed_x}))

[[ 1.74542654  1.74542654  1.74542654]
 [-0.50518501 -0.50518501 -0.50518501]
 [-1.17954302 -1.17954302 -1.17954302]]


#### 6. Indexing

* `indices = tf.to_int64([ , ])`
* `tf.gather_nd(X, indices)`

In [7]:
X = tf.constant([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]], dtype = tf.float32, name = 'X')
element_indices = [[0, 0]]
row_indices = [2]
col_indices = [3]

X_element = tf.gather_nd(X, element_indices)
X_row = tf.gather_nd(X, row_indices)
X_col = tf.gather_nd(tf.transpose(X), col_indices)

with tf.Session() as sess:
    print('X:\n{}\n'.format(sess.run(X)))
    print('X[1, 1]:\n{}\n'.format(sess.run(X_element)))
    print('X[3, :]:\n{}\n'.format(sess.run(X_row)))
    print('X[:, 4]:\n{}\n'.format(sess.run(X_col)))
    

X:
[[  1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.]]

X[1, 1]:
[ 1.]

X[3, :]:
[ 11.  12.  13.  14.  15.]

X[:, 4]:
[  4.   9.  14.]

